workflows:
  android-apk:
    name: Android APK Direct Build

    environment:
      node: latest

    cache:
      cache_paths:
        - ~/.npm

    scripts:
      - rm -rf node_modules
      - rm -f package-lock.json
      - npm install

      # vytvor android priečinok
      - npx expo prebuild --platform android --non-interactive

      # build APK (v jednom riadku!)
      - cd android && chmod +x gradlew && ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
